version: '3.9'

services:
  ninja:
    build:
      context: .
    ports:
      - 8000
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - static_volume:/app/staticfiles
      - .:/app
  
  db:
    image: postgres
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  nginx:
    build:
      context: ./nginx
    ports: 
      - 80:80
    depends_on:
      - ninja
    volumes:
      - static_volume:/app/staticfiles


volumes:
  db_volume:
  static_volume:
